-- Create courses table
CREATE TABLE IF NOT EXISTS courses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    instructor VARCHAR(255) NOT NULL,
    instructor_bio TEXT,
    category VARCHAR(100) NOT NULL,
    level VARCHAR(50) NOT NULL CHECK (level IN ('Beginner', 'Intermediate', 'Advanced')),
    duration_hours INTEGER NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    original_price DECIMAL(10,2),
    rating DECIMAL(3,2) DEFAULT 0.0 CHECK (rating >= 0 AND rating <= 5),
    students_count INTEGER DEFAULT 0,
    reviews_count INTEGER DEFAULT 0,
    image_url TEXT,
    is_featured BOOLEAN DEFAULT FALSE,
    is_trending BOOLEAN DEFAULT FALSE,
    skills TEXT[], -- Array of skills taught
    prerequisites TEXT,
    what_you_learn TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    published_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived'))
);

-- Create an index for better performance
CREATE INDEX IF NOT EXISTS idx_courses_category ON courses(category);
CREATE INDEX IF NOT EXISTS idx_courses_level ON courses(level);
CREATE INDEX IF NOT EXISTS idx_courses_featured ON courses(is_featured);
CREATE INDEX IF NOT EXISTS idx_courses_trending ON courses(is_trending);
CREATE INDEX IF NOT EXISTS idx_courses_status ON courses(status);

-- Insert sample course data
INSERT INTO courses (
    title, 
    description, 
    instructor, 
    instructor_bio,
    category, 
    level, 
    duration_hours, 
    price, 
    original_price, 
    rating, 
    students_count, 
    reviews_count,
    image_url,
    is_featured,
    is_trending,
    skills,
    prerequisites,
    what_you_learn,
    published_at,
    status
) VALUES 
(
    'Complete React Developer Course 2024',
    'Master React from basics to advanced concepts with hands-on projects and real-world applications. Build modern web applications with React, Redux, and the latest JavaScript features.',
    'John Smith',
    'Senior Frontend Developer with 8+ years experience at Google and Meta. Expert in React, JavaScript, and modern web technologies.',
    'Web Development',
    'Beginner',
    12,
    89.99,
    199.99,
    4.8,
    15420,
    2340,
    '/courses/react-course.jpg',
    true,
    true,
    ARRAY['React', 'JavaScript', 'Redux', 'Hooks', 'Context API', 'JSX'],
    'Basic HTML, CSS, and JavaScript knowledge',
    ARRAY['Build complete React applications', 'Master React Hooks', 'Understand Redux state management', 'Create reusable components', 'Deploy React apps to production'],
    NOW(),
    'published'
),
(
    'Python for Data Science & Machine Learning',
    'Complete Python course for data analysis, visualization, and machine learning with real projects. Learn NumPy, Pandas, Matplotlib, and Scikit-learn.',
    'Dr. Sarah Johnson',
    'Data Scientist and AI researcher with PhD in Computer Science. Former lead data scientist at Netflix and Amazon.',
    'Data Science',
    'Intermediate',
    18,
    129.99,
    249.99,
    4.9,
    12850,
    1890,
    '/courses/python-data-science.jpg',
    true,
    true,
    ARRAY['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Scikit-learn', 'Machine Learning'],
    'Basic programming knowledge helpful but not required',
    ARRAY['Master Python for data analysis', 'Create stunning data visualizations', 'Build machine learning models', 'Work with real datasets', 'Deploy ML models'],
    NOW(),
    'published'
),
(
    'Flutter Mobile App Development Masterclass',
    'Build beautiful cross-platform mobile apps with Flutter and Dart programming language. Create iOS and Android apps from a single codebase.',
    'Mike Chen',
    'Mobile app developer with 6+ years experience. Published 20+ apps on App Store and Google Play with millions of downloads.',
    'Mobile Development',
    'Beginner',
    15,
    99.99,
    179.99,
    4.7,
    8950,
    1250,
    '/courses/flutter-masterclass.jpg',
    false,
    true,
    ARRAY['Flutter', 'Dart', 'Mobile UI', 'Firebase', 'State Management', 'API Integration'],
    'No prior mobile development experience needed',
    ARRAY['Build cross-platform mobile apps', 'Master Flutter widgets', 'Integrate with Firebase', 'Publish to app stores', 'Handle state management'],
    NOW(),
    'published'
),
(
    'AWS Cloud Practitioner Certification',
    'Get AWS certified and learn cloud computing fundamentals with hands-on labs. Prepare for the AWS Cloud Practitioner certification exam.',
    'Emily Davis',
    'AWS Solutions Architect with 10+ years in cloud computing. Certified AWS instructor and consultant for Fortune 500 companies.',
    'Cloud Computing',
    'Beginner',
    10,
    79.99,
    149.99,
    4.6,
    11200,
    980,
    '/courses/aws-cloud.jpg',
    false,
    false,
    ARRAY['AWS', 'Cloud Computing', 'EC2', 'S3', 'IAM', 'CloudFormation'],
    'Basic understanding of IT concepts',
    ARRAY['Understand AWS core services', 'Deploy applications on AWS', 'Manage AWS security', 'Pass AWS certification exam', 'Design cloud solutions'],
    NOW(),
    'published'
),
(
    'Machine Learning A-Z: Complete Guide',
    'Complete machine learning course from theory to practical implementation. Build ML models with Python, TensorFlow, and real-world datasets.',
    'Dr. Alex Kumar',
    'Machine Learning Engineer and researcher with PhD in AI. Former senior scientist at OpenAI and Google DeepMind.',
    'Artificial Intelligence',
    'Advanced',
    25,
    149.99,
    299.99,
    4.9,
    9840,
    2100,
    '/courses/machine-learning.jpg',
    true,
    true,
    ARRAY['Machine Learning', 'Python', 'TensorFlow', 'Scikit-learn', 'Deep Learning', 'Neural Networks'],
    'Strong Python programming skills and basic mathematics',
    ARRAY['Master ML algorithms', 'Build neural networks', 'Work with TensorFlow', 'Deploy ML models', 'Understand deep learning'],
    NOW(),
    'published'
),
(
    'Ethical Hacking & Cybersecurity',
    'Learn ethical hacking techniques and cybersecurity best practices. Understand how to secure systems and networks against cyber threats.',
    'James Wilson',
    'Cybersecurity expert with 12+ years experience. Certified Ethical Hacker (CEH) and penetration testing specialist.',
    'Cybersecurity',
    'Intermediate',
    20,
    119.99,
    229.99,
    4.7,
    7650,
    1450,
    '/courses/ethical-hacking.jpg',
    false,
    false,
    ARRAY['Ethical Hacking', 'Penetration Testing', 'Network Security', 'Kali Linux', 'Web Security', 'Cryptography'],
    'Basic networking and system administration knowledge',
    ARRAY['Perform penetration testing', 'Use Kali Linux tools', 'Secure web applications', 'Understand cryptography', 'Conduct security assessments'],
    NOW(),
    'published'
),
(
    'UI/UX Design Masterclass',
    'Master user interface and user experience design principles. Create stunning designs and prototypes using industry-standard tools.',
    'Emma Thompson',
    'Senior UX Designer with 9+ years experience at Apple and Adobe. Expert in design thinking and user-centered design.',
    'Design',
    'Intermediate',
    14,
    109.99,
    199.99,
    4.8,
    13200,
    1680,
    '/courses/uiux-design.jpg',
    true,
    false,
    ARRAY['UI Design', 'UX Design', 'Figma', 'Adobe XD', 'Prototyping', 'Design Thinking'],
    'Basic design knowledge helpful',
    ARRAY['Master design principles', 'Create user-centered designs', 'Build interactive prototypes', 'Conduct user research', 'Design responsive interfaces'],
    NOW(),
    'published'
),
(
    'Node.js Backend Development',
    'Build scalable backend applications with Node.js, Express, and MongoDB. Learn REST APIs, authentication, and deployment strategies.',
    'David Rodriguez',
    'Full-stack developer with 7+ years experience. Lead backend engineer at Spotify and Netflix.',
    'Web Development',
    'Intermediate',
    16,
    94.99,
    169.99,
    4.7,
    10500,
    1320,
    '/courses/nodejs-backend.jpg',
    false,
    true,
    ARRAY['Node.js', 'Express.js', 'MongoDB', 'REST API', 'Authentication', 'GraphQL'],
    'JavaScript fundamentals and basic web development',
    ARRAY['Build REST APIs', 'Handle authentication', 'Work with databases', 'Deploy to cloud', 'Implement real-time features'],
    NOW(),
    'published'
),
(
    'Digital Marketing Mastery 2024',
    'Complete digital marketing course covering SEO, social media, PPC, email marketing, and analytics. Grow your business online.',
    'Lisa Anderson',
    'Digital marketing strategist with 8+ years experience. Helped 200+ businesses grow their online presence.',
    'Digital Marketing',
    'Beginner',
    11,
    84.99,
    159.99,
    4.6,
    14800,
    1950,
    '/courses/digital-marketing.jpg',
    false,
    false,
    ARRAY['SEO', 'Social Media Marketing', 'Google Ads', 'Email Marketing', 'Analytics', 'Content Marketing'],
    'No prior marketing experience needed',
    ARRAY['Master SEO techniques', 'Run effective ad campaigns', 'Build social media presence', 'Analyze marketing data', 'Create content strategies'],
    NOW(),
    'published'
),
(
    'Blockchain Development with Solidity',
    'Learn blockchain development and smart contract programming with Solidity. Build decentralized applications (DApps) on Ethereum.',
    'Robert Kim',
    'Blockchain engineer with 5+ years experience. Lead developer at ConsenSys and founder of multiple DeFi projects.',
    'Blockchain',
    'Advanced',
    22,
    159.99,
    279.99,
    4.8,
    6200,
    890,
    '/courses/blockchain-solidity.jpg',
    true,
    true,
    ARRAY['Blockchain', 'Solidity', 'Ethereum', 'Smart Contracts', 'Web3', 'DeFi'],
    'Strong programming background and basic cryptography knowledge',
    ARRAY['Understand blockchain technology', 'Write smart contracts', 'Build DApps', 'Deploy on Ethereum', 'Implement DeFi protocols'],
    NOW(),
    'published'
);

-- Update the updated_at timestamp trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_courses_updated_at 
    BEFORE UPDATE ON courses 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();