version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: edu-nextjs:prod
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add your env vars or use an env_file
      # - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      # - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    # env_file:
    #   - ./.env
    ports:
      - "3005:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

